/-
Copyright (c) 2026 Hang Lu Su. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Hang Lu Su
-/
module

public import Mathlib.GroupTheory.Presentation

/-!
# Tietze transformations of group presentations

Two presentations describe isomorphic groups if and only if one can be obtained from the other by a
finite sequence of *Tietze transformations*. Working with the bundled `Group.Presentation`, where a
presentation is a chosen presentation of a **fixed** group `G`, each Tietze transformation is an
operation that produces a *new* presentation of the *same* group `G`. There are four elementary
moves, in two mutually inverse pairs:

* **(T1) adding a relator** and **(T1′) removing a relator**: change the family of relators,
  keeping the generators, without changing the normal subgroup they generate;
* **(T2) adding a generator** and **(T2′) removing a generator**: introduce a fresh generator `x`
  together with a relation `x = w` expressing it as a word `w` in the old generators, or the
  reverse.

## Main definitions

* `Group.Presentation.changeRelators`: replace the relators by any family with the same normal
  closure (the primitive behind the relator moves).
* `Group.Presentation.addRelator`: (T1) adjoin a relator `r` that already holds in `G`.
* `Group.Presentation.removeRelator`: (T1′) delete a relator that is a consequence of the others.
* `Group.Presentation.addGenerator`: (T2) adjoin a generator `none` and the defining relator
  `(of none)⁻¹ * map some w`.
* `Group.Presentation.removeGenerator`: (T2′) delete the generator `none` and its defining
  relator, substituting the word `w` for `none` throughout.

## Implementation notes

The generator moves are stated using `Option`: adding a generator sends the index type `α` to
`Option α`, with the fresh generator being `none`; removing a generator is the reverse. The
substitution "replace the fresh generator by the word `w`" is realised by the retraction
`FreeGroup.substNone w : FreeGroup (Option α) →* FreeGroup α`, a section of
`FreeGroup.map Option.some`.

## Tags

Tietze transformation, group presentation, generators and relations
-/

@[expose] public section

namespace FreeGroup

variable {α β γ : Type*}

/-- Precomposing a lift with a `map` is the lift of the composite:
`lift g ∘ map f = lift (g ∘ f)`. -/
theorem lift_comp_map [Group γ] (g : β → γ) (f : α → β) :
    (FreeGroup.lift g).comp (FreeGroup.map f) = FreeGroup.lift (g ∘ f) := by
  refine FreeGroup.ext_hom _ _ fun a => ?_
  simp

/-- The retraction `FreeGroup (Option α) →* FreeGroup α` that fixes every "old" generator
`some a` and substitutes the word `w` for the "new" generator `none`. It is a section of
`FreeGroup.map Option.some`, and is the substitution used to add or remove a generator in a
Tietze transformation. -/
def substNone (w : FreeGroup α) : FreeGroup (Option α) →* FreeGroup α :=
  FreeGroup.lift fun o => o.elim w FreeGroup.of

@[simp] theorem substNone_of_none (w : FreeGroup α) :
    substNone w (FreeGroup.of none) = w := by simp [substNone]

@[simp] theorem substNone_of_some (w : FreeGroup α) (a : α) :
    substNone w (FreeGroup.of (some a)) = FreeGroup.of a := by simp [substNone]

theorem substNone_comp_map (w : FreeGroup α) :
    (substNone w).comp (FreeGroup.map Option.some) = MonoidHom.id (FreeGroup α) := by
  refine FreeGroup.ext_hom _ _ fun a => ?_
  simp

@[simp] theorem substNone_map_some (w x : FreeGroup α) :
    substNone w (FreeGroup.map Option.some x) = x := by
  have := substNone_comp_map w
  rw [← MonoidHom.comp_apply, this, MonoidHom.id_apply]

theorem substNone_surjective (w : FreeGroup α) : Function.Surjective (substNone w) := by
  have h : Function.Surjective
      (⇑(substNone w) ∘ ⇑(FreeGroup.map (Option.some : α → Option α))) := by
    rw [← MonoidHom.coe_comp, substNone_comp_map, MonoidHom.coe_id]
    exact Function.surjective_id
  exact h.of_comp

/-- The kernel of `substNone w` is normally generated by the single defining relator
`(of none)⁻¹ * map some w`. This is the fact that adjoining a generator with a defining relation
does not change the group. -/
theorem ker_substNone (w : FreeGroup α) :
    (substNone w).ker
      = Subgroup.normalClosure {(FreeGroup.of none)⁻¹ * FreeGroup.map Option.some w} := by
  apply le_antisymm
  · intro u hu
    rw [MonoidHom.mem_ker] at hu
    set N := Subgroup.normalClosure
      ({(FreeGroup.of none)⁻¹ * FreeGroup.map Option.some w} : Set (FreeGroup (Option α)))
    have hmk : (QuotientGroup.mk' N) (FreeGroup.of none)
        = (QuotientGroup.mk' N) (FreeGroup.map Option.some w) := by
      have ht1 : (QuotientGroup.mk' N)
          ((FreeGroup.of none)⁻¹ * FreeGroup.map Option.some w) = 1 := by
        rw [← MonoidHom.mem_ker, QuotientGroup.ker_mk']
        exact Subgroup.subset_normalClosure rfl
      rwa [_root_.map_mul, _root_.map_inv, inv_mul_eq_one] at ht1
    have hcomp : (QuotientGroup.mk' N)
        = ((QuotientGroup.mk' N).comp (FreeGroup.map Option.some)).comp (substNone w) := by
      refine FreeGroup.ext_hom _ _ fun o => ?_
      cases o with
      | none => simpa [substNone_of_none] using hmk
      | some a => simp [substNone_of_some]
    have hu1 : (QuotientGroup.mk' N) u = 1 := by
      rw [hcomp]; simp [hu]
    rwa [← MonoidHom.mem_ker, QuotientGroup.ker_mk'] at hu1
  · apply Subgroup.normalClosure_le_normal
    rw [Set.singleton_subset_iff, SetLike.mem_coe, MonoidHom.mem_ker, _root_.map_mul,
      _root_.map_inv, substNone_of_none, substNone_map_some, inv_mul_cancel]

end FreeGroup

namespace Subgroup

variable {G : Type*} [Group G] {s : Set G} {x : G}

/-- Adjoining to a set an element already in its normal closure leaves the normal closure fixed. -/
theorem normalClosure_insert_of_mem (hx : x ∈ normalClosure s) :
    normalClosure (insert x s) = normalClosure s :=
  le_antisymm
    (normalClosure_le_normal (Set.insert_subset_iff.mpr ⟨hx, subset_normalClosure⟩))
    (normalClosure_mono (Set.subset_insert x s))

/-- Adjoining the identity to a set does not change its normal closure. -/
theorem normalClosure_insert_one (s : Set G) :
    normalClosure (insert 1 s) = normalClosure s :=
  normalClosure_insert_of_mem (one_mem _)

end Subgroup

namespace Group.Presentation

variable {G α ρ : Type*} [Group G]

/-- **Change of relators.** Replace the relators of `P` by any family `r` whose normal closure is
still the kernel of `P.lift`, keeping the generators. This is the primitive underlying the Tietze
relator moves `addRelator` and `removeRelator`. -/
def changeRelators (P : Group.Presentation G α ρ) {σ : Type*} (r : σ → FreeGroup α)
    (h : Subgroup.normalClosure (Set.range r) = P.lift.ker) : Group.Presentation G α σ where
  val := P.val
  lift_surjective := P.lift_surjective
  rel := r
  ker_eq_normalClosure := h.symm

@[simp] theorem changeRelators_val (P : Group.Presentation G α ρ) {σ : Type*}
    (r : σ → FreeGroup α) (h : Subgroup.normalClosure (Set.range r) = P.lift.ker) :
    (P.changeRelators r h).val = P.val := rfl

@[simp] theorem changeRelators_rel (P : Group.Presentation G α ρ) {σ : Type*}
    (r : σ → FreeGroup α) (h : Subgroup.normalClosure (Set.range r) = P.lift.ker) :
    (P.changeRelators r h).rel = r := rfl

/-- **(T1) Adding a relator.** Adjoin to the relators a word `r` that already holds in `G`
(`P.lift r = 1`). The result presents the same group `G`, indexed by `Option ρ` with the new
relator sitting at `none`. -/
def addRelator (P : Group.Presentation G α ρ) (r : FreeGroup α) (hr : P.lift r = 1) :
    Group.Presentation G α (Option ρ) :=
  P.changeRelators (fun o => o.elim r P.rel) <| by
    have hr' : r ∈ Subgroup.normalClosure (Set.range P.rel) := by
      rw [show Subgroup.normalClosure (Set.range P.rel) = P.lift.ker
          from P.ker_eq_normalClosure.symm, MonoidHom.mem_ker]
      exact hr
    rw [Option.range_elim, Subgroup.normalClosure_insert_of_mem hr']
    exact P.ker_eq_normalClosure.symm

@[simp] theorem addRelator_val (P : Group.Presentation G α ρ) (r : FreeGroup α)
    (hr : P.lift r = 1) : (P.addRelator r hr).val = P.val := rfl

@[simp] theorem addRelator_rel_none (P : Group.Presentation G α ρ) (r : FreeGroup α)
    (hr : P.lift r = 1) : (P.addRelator r hr).rel none = r := rfl

@[simp] theorem addRelator_rel_some (P : Group.Presentation G α ρ) (r : FreeGroup α)
    (hr : P.lift r = 1) (s : ρ) : (P.addRelator r hr).rel (some s) = P.rel s := rfl

/-- **(T1′) Removing a relator.** Delete the relator indexed by `none` from a presentation over
`Option ρ`, provided it is a consequence of the remaining relators (it lies in their normal
closure). The result presents the same group `G`, indexed by `ρ`. -/
def removeRelator (P : Group.Presentation G α (Option ρ))
    (hr : P.rel none ∈ Subgroup.normalClosure (Set.range (P.rel ∘ Option.some))) :
    Group.Presentation G α ρ :=
  P.changeRelators (P.rel ∘ Option.some) <| by
    rw [show P.lift.ker = Subgroup.normalClosure (Set.range P.rel) from P.ker_eq_normalClosure,
      Option.range_eq P.rel, Subgroup.normalClosure_insert_of_mem hr]

@[simp] theorem removeRelator_val (P : Group.Presentation G α (Option ρ))
    (hr : P.rel none ∈ Subgroup.normalClosure (Set.range (P.rel ∘ Option.some))) :
    (P.removeRelator hr).val = P.val := rfl

@[simp] theorem removeRelator_rel (P : Group.Presentation G α (Option ρ))
    (hr : P.rel none ∈ Subgroup.normalClosure (Set.range (P.rel ∘ Option.some))) (s : ρ) :
    (P.removeRelator hr).rel s = P.rel (some s) := rfl

/-- The `lift` of the presentation obtained by adding a generator factors through the substitution
`FreeGroup.substNone w`. -/
theorem addGenerator_lift_eq (P : Group.Presentation G α ρ) (w : FreeGroup α) :
    FreeGroup.lift (fun o : Option α => o.elim (P.lift w) P.val)
      = P.lift.comp (FreeGroup.substNone w) := by
  refine FreeGroup.ext_hom _ _ fun o => ?_
  cases o with
  | none => simp [FreeGroup.substNone_of_none]
  | some a => simp [FreeGroup.substNone_of_some]

/-- **(T2) Adding a generator.** Introduce a fresh generator `none` whose value is `P.lift w`, for
a chosen word `w` in the old generators, together with the defining relator
`(of none)⁻¹ * map some w`. The result presents the same group `G`, indexed by `Option α` and
`Option ρ`. -/
def addGenerator (P : Group.Presentation G α ρ) (w : FreeGroup α) :
    Group.Presentation G (Option α) (Option ρ) where
  val := fun o => o.elim (P.lift w) P.val
  lift_surjective := by
    rw [addGenerator_lift_eq, MonoidHom.coe_comp]
    exact P.lift_surjective'.comp (FreeGroup.substNone_surjective w)
  rel := fun o => o.elim ((FreeGroup.of none)⁻¹ * FreeGroup.map Option.some w)
    fun s => FreeGroup.map Option.some (P.rel s)
  ker_eq_normalClosure := by
    rw [addGenerator_lift_eq, ← MonoidHom.comap_ker,
      show (Group.Presentation.lift P).ker = Subgroup.normalClosure (Set.range P.rel) from
        P.ker_eq_normalClosure, Option.range_elim]
    set f := FreeGroup.substNone w
    set S := Set.range P.rel
    set t : FreeGroup (Option α) := (FreeGroup.of none)⁻¹ * FreeGroup.map Option.some w with ht
    set R := insert t (Set.range fun s => FreeGroup.map Option.some (P.rel s)) with hR
    haveI : ((Subgroup.normalClosure S).comap f).Normal :=
      (Subgroup.normalClosure_normal).comap f
    apply le_antisymm
    · -- `comap f (normalClosure S) ≤ normalClosure R`
      intro u hu
      rw [Subgroup.mem_comap] at hu
      have h1 : u * (FreeGroup.map Option.some (f u))⁻¹ ∈ Subgroup.normalClosure R := by
        have hker : u * (FreeGroup.map Option.some (f u))⁻¹ ∈ f.ker := by
          rw [MonoidHom.mem_ker, map_mul, map_inv, FreeGroup.substNone_map_some, mul_inv_cancel]
        rw [FreeGroup.ker_substNone] at hker
        exact Subgroup.normalClosure_mono
          (Set.singleton_subset_iff.mpr (Set.mem_insert _ _)) hker
      have h2 : FreeGroup.map Option.some (f u) ∈ Subgroup.normalClosure R := by
        have hle : (Subgroup.normalClosure S).map (FreeGroup.map Option.some)
            ≤ Subgroup.normalClosure (FreeGroup.map Option.some '' S) :=
          Subgroup.map_normalClosure_le S _
        have hsub : (FreeGroup.map Option.some '' S) ⊆ R := by
          rintro _ ⟨y, ⟨s, rfl⟩, rfl⟩
          exact Set.mem_insert_of_mem _ ⟨s, rfl⟩
        exact Subgroup.normalClosure_mono hsub
          (hle (Subgroup.mem_map_of_mem _ hu))
      simpa using (Subgroup.normalClosure R).mul_mem h1 h2
    · -- `normalClosure R ≤ comap f (normalClosure S)`
      apply Subgroup.normalClosure_le_normal
      rw [hR, Set.insert_subset_iff]
      refine ⟨?_, ?_⟩
      · rw [SetLike.mem_coe, Subgroup.mem_comap, ht, map_mul, map_inv,
          FreeGroup.substNone_of_none, FreeGroup.substNone_map_some, inv_mul_cancel]
        exact one_mem _
      · rintro _ ⟨s, rfl⟩
        rw [SetLike.mem_coe, Subgroup.mem_comap, FreeGroup.substNone_map_some]
        exact Subgroup.subset_normalClosure ⟨s, rfl⟩

@[simp] theorem addGenerator_val_none (P : Group.Presentation G α ρ) (w : FreeGroup α) :
    (P.addGenerator w).val none = P.lift w := rfl

@[simp] theorem addGenerator_val_some (P : Group.Presentation G α ρ) (w : FreeGroup α) (a : α) :
    (P.addGenerator w).val (some a) = P.val a := rfl

@[simp] theorem addGenerator_rel_none (P : Group.Presentation G α ρ) (w : FreeGroup α) :
    (P.addGenerator w).rel none = (FreeGroup.of none)⁻¹ * FreeGroup.map Option.some w := rfl

@[simp] theorem addGenerator_rel_some (P : Group.Presentation G α ρ) (w : FreeGroup α) (s : ρ) :
    (P.addGenerator w).rel (some s) = FreeGroup.map Option.some (P.rel s) := rfl

/-- The `lift` of a presentation over `Option α` whose relator `none` is
`(of none)⁻¹ * map some w` factors through the substitution `FreeGroup.substNone w`. -/
theorem removeGenerator_lift_eq (P : Group.Presentation G (Option α) (Option ρ))
    (w : FreeGroup α)
    (hrel : P.rel none = (FreeGroup.of none)⁻¹ * FreeGroup.map Option.some w) :
    P.lift = (FreeGroup.lift fun a => P.val (some a)).comp (FreeGroup.substNone w) := by
  have hmap : (FreeGroup.lift fun a => P.val (some a)) w
      = P.lift (FreeGroup.map Option.some w) := by
    rw [Group.Presentation.lift, show (fun a => P.val (some a)) = P.val ∘ Option.some from rfl,
      ← FreeGroup.lift_comp_map, MonoidHom.comp_apply]
  have hval : P.val none = (FreeGroup.lift fun a => P.val (some a)) w := by
    have h1 := P.lift_rel none
    rw [hrel, map_mul, map_inv, P.lift_of, ← hmap, inv_mul_eq_one] at h1
    exact h1
  refine FreeGroup.ext_hom _ _ fun o => ?_
  cases o with
  | none => simp [FreeGroup.substNone_of_none, hval]
  | some a => simp [FreeGroup.substNone_of_some]

/-- **(T2′) Removing a generator.** Delete the generator `none` and its defining relator
`P.rel none = (of none)⁻¹ * map some w`, substituting the word `w` for `none` in every other
relator. The result presents the same group `G`, indexed by `α` and `ρ`. -/
def removeGenerator (P : Group.Presentation G (Option α) (Option ρ)) (w : FreeGroup α)
    (hrel : P.rel none = (FreeGroup.of none)⁻¹ * FreeGroup.map Option.some w) :
    Group.Presentation G α ρ where
  val := fun a => P.val (some a)
  lift_surjective := by
    have h : Function.Surjective
        (⇑(FreeGroup.lift fun a => P.val (some a)) ∘ ⇑(FreeGroup.substNone w)) := by
      rw [← MonoidHom.coe_comp, ← removeGenerator_lift_eq P w hrel]
      exact P.lift_surjective'
    exact h.of_comp
  rel := fun s => FreeGroup.substNone w (P.rel (some s))
  ker_eq_normalClosure := by
    have hval1 : FreeGroup.substNone w (P.rel none) = 1 := by
      rw [hrel, map_mul, map_inv, FreeGroup.substNone_of_none, FreeGroup.substNone_map_some,
        inv_mul_cancel]
    have hker : (FreeGroup.lift fun a => P.val (some a)).ker
        = (Subgroup.normalClosure (Set.range P.rel)).map (FreeGroup.substNone w) := by
      rw [← Subgroup.map_comap_eq_self_of_surjective (FreeGroup.substNone_surjective w)
          (FreeGroup.lift fun a => P.val (some a)).ker, MonoidHom.comap_ker,
        ← removeGenerator_lift_eq P w hrel,
        show (Group.Presentation.lift P).ker = Subgroup.normalClosure (Set.range P.rel) from
          P.ker_eq_normalClosure]
    rw [hker, Subgroup.map_normalClosure _ _ (FreeGroup.substNone_surjective w)]
    have himg : FreeGroup.substNone w '' Set.range P.rel
        = insert 1 (Set.range fun s => FreeGroup.substNone w (P.rel (some s))) := by
      rw [Option.range_eq P.rel, Set.image_insert_eq, hval1, ← Set.range_comp]
      rfl
    rw [himg, Subgroup.normalClosure_insert_one]

@[simp] theorem removeGenerator_val (P : Group.Presentation G (Option α) (Option ρ))
    (w : FreeGroup α) (hrel : P.rel none = (FreeGroup.of none)⁻¹ * FreeGroup.map Option.some w)
    (a : α) : (P.removeGenerator w hrel).val a = P.val (some a) := rfl

@[simp] theorem removeGenerator_rel (P : Group.Presentation G (Option α) (Option ρ))
    (w : FreeGroup α) (hrel : P.rel none = (FreeGroup.of none)⁻¹ * FreeGroup.map Option.some w)
    (s : ρ) : (P.removeGenerator w hrel).rel s = FreeGroup.substNone w (P.rel (some s)) := rfl

end Group.Presentation
